<table>
    <tr>
        <th>Id</th>
        <th>Number</th>
        <th>Year</th>
        <th>Note</th>
        <th>Action</th>
    </tr>
    <tr>
        <td>{{$truck->id}}</td>
        <td>{{$truck->unit_number}}</td>
        <td>{{$truck->year}}</td>
        <td>{{$truck->note}}</td>
        <td>edit,delete</td>
    </tr>
</table>